set WFDB=C:\Users\Public\Work\ecg_viewer\assets\ECG_DB\MITDB;
: file: MIT-valid.bat	ecgeval		30 July 2026
:
: Evaluate test annotator gqrs on the MIT DB

: This file was automatically generated by ecgeval.  Do not edit it
: unless you know what you are doing!

: Record 100
bxb -r 100 -a atr gqrs -l bxb.out sd.out
rxr -r 100 -a atr gqrs -l vruns.out 
mxm -r 100 -a atr gqrs -L hr0.out -m 0

: Record 101
bxb -r 101 -a atr gqrs -l bxb.out sd.out
rxr -r 101 -a atr gqrs -l vruns.out 
mxm -r 101 -a atr gqrs -L hr0.out -m 0

: Record 102
bxb -r 102 -a atr gqrs -l bxb.out sd.out
rxr -r 102 -a atr gqrs -l vruns.out 
mxm -r 102 -a atr gqrs -L hr0.out -m 0

: Record 103
bxb -r 103 -a atr gqrs -l bxb.out sd.out
rxr -r 103 -a atr gqrs -l vruns.out 
mxm -r 103 -a atr gqrs -L hr0.out -m 0

: Record 104
bxb -r 104 -a atr gqrs -l bxb.out sd.out
rxr -r 104 -a atr gqrs -l vruns.out 
mxm -r 104 -a atr gqrs -L hr0.out -m 0

: Record 105
bxb -r 105 -a atr gqrs -l bxb.out sd.out
rxr -r 105 -a atr gqrs -l vruns.out 
mxm -r 105 -a atr gqrs -L hr0.out -m 0

: Record 106
bxb -r 106 -a atr gqrs -l bxb.out sd.out
rxr -r 106 -a atr gqrs -l vruns.out 
mxm -r 106 -a atr gqrs -L hr0.out -m 0

: Record 107
bxb -r 107 -a atr gqrs -l bxb.out sd.out
rxr -r 107 -a atr gqrs -l vruns.out 
mxm -r 107 -a atr gqrs -L hr0.out -m 0

: Record 108
bxb -r 108 -a atr gqrs -l bxb.out sd.out
rxr -r 108 -a atr gqrs -l vruns.out 
mxm -r 108 -a atr gqrs -L hr0.out -m 0

: Record 109
bxb -r 109 -a atr gqrs -l bxb.out sd.out
rxr -r 109 -a atr gqrs -l vruns.out 
mxm -r 109 -a atr gqrs -L hr0.out -m 0

: Record 111
bxb -r 111 -a atr gqrs -l bxb.out sd.out
rxr -r 111 -a atr gqrs -l vruns.out 
mxm -r 111 -a atr gqrs -L hr0.out -m 0

: Record 112
bxb -r 112 -a atr gqrs -l bxb.out sd.out
rxr -r 112 -a atr gqrs -l vruns.out 
mxm -r 112 -a atr gqrs -L hr0.out -m 0

: Record 113
bxb -r 113 -a atr gqrs -l bxb.out sd.out
rxr -r 113 -a atr gqrs -l vruns.out 
mxm -r 113 -a atr gqrs -L hr0.out -m 0

: Record 114
bxb -r 114 -a atr gqrs -l bxb.out sd.out
rxr -r 114 -a atr gqrs -l vruns.out 
mxm -r 114 -a atr gqrs -L hr0.out -m 0

: Record 115
bxb -r 115 -a atr gqrs -l bxb.out sd.out
rxr -r 115 -a atr gqrs -l vruns.out 
mxm -r 115 -a atr gqrs -L hr0.out -m 0

: Record 116
bxb -r 116 -a atr gqrs -l bxb.out sd.out
rxr -r 116 -a atr gqrs -l vruns.out 
mxm -r 116 -a atr gqrs -L hr0.out -m 0

: Record 117
bxb -r 117 -a atr gqrs -l bxb.out sd.out
rxr -r 117 -a atr gqrs -l vruns.out 
mxm -r 117 -a atr gqrs -L hr0.out -m 0

: Record 118
bxb -r 118 -a atr gqrs -l bxb.out sd.out
rxr -r 118 -a atr gqrs -l vruns.out 
mxm -r 118 -a atr gqrs -L hr0.out -m 0

: Record 119
bxb -r 119 -a atr gqrs -l bxb.out sd.out
rxr -r 119 -a atr gqrs -l vruns.out 
mxm -r 119 -a atr gqrs -L hr0.out -m 0

: Record 121
bxb -r 121 -a atr gqrs -l bxb.out sd.out
rxr -r 121 -a atr gqrs -l vruns.out 
mxm -r 121 -a atr gqrs -L hr0.out -m 0

: Record 122
bxb -r 122 -a atr gqrs -l bxb.out sd.out
rxr -r 122 -a atr gqrs -l vruns.out 
mxm -r 122 -a atr gqrs -L hr0.out -m 0

: Record 123
bxb -r 123 -a atr gqrs -l bxb.out sd.out
rxr -r 123 -a atr gqrs -l vruns.out 
mxm -r 123 -a atr gqrs -L hr0.out -m 0

: Record 124
bxb -r 124 -a atr gqrs -l bxb.out sd.out
rxr -r 124 -a atr gqrs -l vruns.out 
mxm -r 124 -a atr gqrs -L hr0.out -m 0

: Record 200
bxb -r 200 -a atr gqrs -l bxb.out sd.out
rxr -r 200 -a atr gqrs -l vruns.out 
mxm -r 200 -a atr gqrs -L hr0.out -m 0

: Record 201
bxb -r 201 -a atr gqrs -l bxb.out sd.out
rxr -r 201 -a atr gqrs -l vruns.out 
mxm -r 201 -a atr gqrs -L hr0.out -m 0

: Record 202
bxb -r 202 -a atr gqrs -l bxb.out sd.out
rxr -r 202 -a atr gqrs -l vruns.out 
mxm -r 202 -a atr gqrs -L hr0.out -m 0

: Record 203
bxb -r 203 -a atr gqrs -l bxb.out sd.out
rxr -r 203 -a atr gqrs -l vruns.out 
mxm -r 203 -a atr gqrs -L hr0.out -m 0

: Record 205
bxb -r 205 -a atr gqrs -l bxb.out sd.out
rxr -r 205 -a atr gqrs -l vruns.out 
mxm -r 205 -a atr gqrs -L hr0.out -m 0

: Record 207
bxb -r 207 -a atr gqrs -l bxb.out sd.out
rxr -r 207 -a atr gqrs -l vruns.out 
mxm -r 207 -a atr gqrs -L hr0.out -m 0

: Record 208
bxb -r 208 -a atr gqrs -l bxb.out sd.out
rxr -r 208 -a atr gqrs -l vruns.out 
mxm -r 208 -a atr gqrs -L hr0.out -m 0

: Record 209
bxb -r 209 -a atr gqrs -l bxb.out sd.out
rxr -r 209 -a atr gqrs -l vruns.out 
mxm -r 209 -a atr gqrs -L hr0.out -m 0

: Record 210
bxb -r 210 -a atr gqrs -l bxb.out sd.out
rxr -r 210 -a atr gqrs -l vruns.out 
mxm -r 210 -a atr gqrs -L hr0.out -m 0

: Record 212
bxb -r 212 -a atr gqrs -l bxb.out sd.out
rxr -r 212 -a atr gqrs -l vruns.out 
mxm -r 212 -a atr gqrs -L hr0.out -m 0

: Record 213
bxb -r 213 -a atr gqrs -l bxb.out sd.out
rxr -r 213 -a atr gqrs -l vruns.out 
mxm -r 213 -a atr gqrs -L hr0.out -m 0

: Record 214
bxb -r 214 -a atr gqrs -l bxb.out sd.out
rxr -r 214 -a atr gqrs -l vruns.out 
mxm -r 214 -a atr gqrs -L hr0.out -m 0

: Record 215
bxb -r 215 -a atr gqrs -l bxb.out sd.out
rxr -r 215 -a atr gqrs -l vruns.out 
mxm -r 215 -a atr gqrs -L hr0.out -m 0

: Record 217
bxb -r 217 -a atr gqrs -l bxb.out sd.out
rxr -r 217 -a atr gqrs -l vruns.out 
mxm -r 217 -a atr gqrs -L hr0.out -m 0

: Record 219
bxb -r 219 -a atr gqrs -l bxb.out sd.out
rxr -r 219 -a atr gqrs -l vruns.out 
mxm -r 219 -a atr gqrs -L hr0.out -m 0

: Record 220
bxb -r 220 -a atr gqrs -l bxb.out sd.out
rxr -r 220 -a atr gqrs -l vruns.out 
mxm -r 220 -a atr gqrs -L hr0.out -m 0

: Record 221
bxb -r 221 -a atr gqrs -l bxb.out sd.out
rxr -r 221 -a atr gqrs -l vruns.out 
mxm -r 221 -a atr gqrs -L hr0.out -m 0

: Record 222
bxb -r 222 -a atr gqrs -l bxb.out sd.out
rxr -r 222 -a atr gqrs -l vruns.out 
mxm -r 222 -a atr gqrs -L hr0.out -m 0

: Record 223
bxb -r 223 -a atr gqrs -l bxb.out sd.out
rxr -r 223 -a atr gqrs -l vruns.out 
mxm -r 223 -a atr gqrs -L hr0.out -m 0

: Record 228
bxb -r 228 -a atr gqrs -l bxb.out sd.out
rxr -r 228 -a atr gqrs -l vruns.out 
mxm -r 228 -a atr gqrs -L hr0.out -m 0

: Record 230
bxb -r 230 -a atr gqrs -l bxb.out sd.out
rxr -r 230 -a atr gqrs -l vruns.out 
mxm -r 230 -a atr gqrs -L hr0.out -m 0

: Record 231
bxb -r 231 -a atr gqrs -l bxb.out sd.out
rxr -r 231 -a atr gqrs -l vruns.out 
mxm -r 231 -a atr gqrs -L hr0.out -m 0

: Record 232
bxb -r 232 -a atr gqrs -l bxb.out sd.out
rxr -r 232 -a atr gqrs -l vruns.out 
mxm -r 232 -a atr gqrs -L hr0.out -m 0

: Record 233
bxb -r 233 -a atr gqrs -l bxb.out sd.out
rxr -r 233 -a atr gqrs -l vruns.out 
mxm -r 233 -a atr gqrs -L hr0.out -m 0

: Record 234
bxb -r 234 -a atr gqrs -l bxb.out sd.out
rxr -r 234 -a atr gqrs -l vruns.out 
mxm -r 234 -a atr gqrs -L hr0.out -m 0

: Generate summary report
echo Beat detection and classification performance >>MIT-report.txt
echo >>MIT-report.txt
sumstats bxb.out >>MIT-report.txt
echo >>MIT-report.txt
echo Analysis shutdowns >>MIT-report.txt
echo >>MIT-report.txt
sumstats sd.out >>MIT-report.txt
echo >>MIT-report.txt
echo Ventricular ectopic run detection performance >>MIT-report.txt
echo >>MIT-report.txt
sumstats vruns.out >>MIT-report.txt
echo >>MIT-report.txt
echo Heart rate measurement number 0 performance >>MIT-report.txt
echo >>MIT-report.txt
sumstats hr0.out >>MIT-report.txt
echo >>MIT-report.txt
echo The evaluation is complete.  Print text file MIT-report.txt
echo to get the results.
