set WFDB=C:\Users\Public\Work\ecg_viewer\assets\ECG_DB\AHADB;
: file: AHA-valid.bat	ecgeval		30 July 2026
:
: Evaluate test annotator gqrs on the AHA DB

: This file was automatically generated by ecgeval.  Do not edit it
: unless you know what you are doing!

: Record 1201
bxb -r 1201 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 1201 -a atr gqrs -l vruns_AHA.out 
mxm -r 1201 -a atr gqrs -L hr0.out -m 0

: Record 1202
bxb -r 1202 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 1202 -a atr gqrs -l vruns_AHA.out 
mxm -r 1202 -a atr gqrs -L hr0.out -m 0

: Record 1203
bxb -r 1203 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 1203 -a atr gqrs -l vruns_AHA.out 
mxm -r 1203 -a atr gqrs -L hr0.out -m 0

: Record 1204
bxb -r 1204 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 1204 -a atr gqrs -l vruns_AHA.out 
mxm -r 1204 -a atr gqrs -L hr0.out -m 0

: Record 1205
bxb -r 1205 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 1205 -a atr gqrs -l vruns_AHA.out 
mxm -r 1205 -a atr gqrs -L hr0.out -m 0

: Record 1206
bxb -r 1206 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 1206 -a atr gqrs -l vruns_AHA.out 
mxm -r 1206 -a atr gqrs -L hr0.out -m 0

: Record 1207
bxb -r 1207 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 1207 -a atr gqrs -l vruns_AHA.out 
mxm -r 1207 -a atr gqrs -L hr0.out -m 0

: Record 2201
bxb -r 2201 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 2201 -a atr gqrs -l vruns_AHA.out 
mxm -r 2201 -a atr gqrs -L hr0.out -m 0

: Record 2202
bxb -r 2202 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 2202 -a atr gqrs -l vruns_AHA.out 
mxm -r 2202 -a atr gqrs -L hr0.out -m 0

: Record 2203
bxb -r 2203 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 2203 -a atr gqrs -l vruns_AHA.out 
mxm -r 2203 -a atr gqrs -L hr0.out -m 0

: Record 2204
bxb -r 2204 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 2204 -a atr gqrs -l vruns_AHA.out 
mxm -r 2204 -a atr gqrs -L hr0.out -m 0

: Record 2205
bxb -r 2205 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 2205 -a atr gqrs -l vruns_AHA.out 
mxm -r 2205 -a atr gqrs -L hr0.out -m 0

: Record 2206
bxb -r 2206 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 2206 -a atr gqrs -l vruns_AHA.out 
mxm -r 2206 -a atr gqrs -L hr0.out -m 0

: Record 2207
bxb -r 2207 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 2207 -a atr gqrs -l vruns_AHA.out 
mxm -r 2207 -a atr gqrs -L hr0.out -m 0

: Record 3201
bxb -r 3201 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 3201 -a atr gqrs -l vruns_AHA.out 
mxm -r 3201 -a atr gqrs -L hr0.out -m 0

: Record 3202
bxb -r 3202 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 3202 -a atr gqrs -l vruns_AHA.out 
mxm -r 3202 -a atr gqrs -L hr0.out -m 0

: Record 3203
bxb -r 3203 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 3203 -a atr gqrs -l vruns_AHA.out 
mxm -r 3203 -a atr gqrs -L hr0.out -m 0

: Record 3204
bxb -r 3204 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 3204 -a atr gqrs -l vruns_AHA.out 
mxm -r 3204 -a atr gqrs -L hr0.out -m 0

: Record 3205
bxb -r 3205 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 3205 -a atr gqrs -l vruns_AHA.out 
mxm -r 3205 -a atr gqrs -L hr0.out -m 0

: Record 3206
bxb -r 3206 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 3206 -a atr gqrs -l vruns_AHA.out 
mxm -r 3206 -a atr gqrs -L hr0.out -m 0

: Record 3207
bxb -r 3207 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 3207 -a atr gqrs -l vruns_AHA.out 
mxm -r 3207 -a atr gqrs -L hr0.out -m 0

: Record 4201
bxb -r 4201 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 4201 -a atr gqrs -l vruns_AHA.out 
mxm -r 4201 -a atr gqrs -L hr0.out -m 0

: Record 4202
bxb -r 4202 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 4202 -a atr gqrs -l vruns_AHA.out 
mxm -r 4202 -a atr gqrs -L hr0.out -m 0

: Record 4203
bxb -r 4203 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 4203 -a atr gqrs -l vruns_AHA.out 
mxm -r 4203 -a atr gqrs -L hr0.out -m 0

: Record 4204
bxb -r 4204 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 4204 -a atr gqrs -l vruns_AHA.out 
mxm -r 4204 -a atr gqrs -L hr0.out -m 0

: Record 4205
bxb -r 4205 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 4205 -a atr gqrs -l vruns_AHA.out 
mxm -r 4205 -a atr gqrs -L hr0.out -m 0

: Record 4206
bxb -r 4206 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 4206 -a atr gqrs -l vruns_AHA.out 
mxm -r 4206 -a atr gqrs -L hr0.out -m 0

: Record 4207
bxb -r 4207 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 4207 -a atr gqrs -l vruns_AHA.out 
mxm -r 4207 -a atr gqrs -L hr0.out -m 0

: Record 5201
bxb -r 5201 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 5201 -a atr gqrs -l vruns_AHA.out 
mxm -r 5201 -a atr gqrs -L hr0.out -m 0

: Record 5202
bxb -r 5202 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 5202 -a atr gqrs -l vruns_AHA.out 
mxm -r 5202 -a atr gqrs -L hr0.out -m 0

: Record 5203
bxb -r 5203 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 5203 -a atr gqrs -l vruns_AHA.out 
mxm -r 5203 -a atr gqrs -L hr0.out -m 0

: Record 5204
bxb -r 5204 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 5204 -a atr gqrs -l vruns_AHA.out 
mxm -r 5204 -a atr gqrs -L hr0.out -m 0

: Record 5205
bxb -r 5205 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 5205 -a atr gqrs -l vruns_AHA.out 
mxm -r 5205 -a atr gqrs -L hr0.out -m 0

: Record 5206
bxb -r 5206 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 5206 -a atr gqrs -l vruns_AHA.out 
mxm -r 5206 -a atr gqrs -L hr0.out -m 0

: Record 5207
bxb -r 5207 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 5207 -a atr gqrs -l vruns_AHA.out 
mxm -r 5207 -a atr gqrs -L hr0.out -m 0

: Record 6201
bxb -r 6201 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 6201 -a atr gqrs -l vruns_AHA.out 
mxm -r 6201 -a atr gqrs -L hr0.out -m 0

: Record 6202
bxb -r 6202 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 6202 -a atr gqrs -l vruns_AHA.out 
mxm -r 6202 -a atr gqrs -L hr0.out -m 0

: Record 6203
bxb -r 6203 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 6203 -a atr gqrs -l vruns_AHA.out 
mxm -r 6203 -a atr gqrs -L hr0.out -m 0

: Record 6204
bxb -r 6204 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 6204 -a atr gqrs -l vruns_AHA.out 
mxm -r 6204 -a atr gqrs -L hr0.out -m 0

: Record 6205
bxb -r 6205 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 6205 -a atr gqrs -l vruns_AHA.out 
mxm -r 6205 -a atr gqrs -L hr0.out -m 0

: Record 6206
bxb -r 6206 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 6206 -a atr gqrs -l vruns_AHA.out 
mxm -r 6206 -a atr gqrs -L hr0.out -m 0

: Record 6207
bxb -r 6207 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 6207 -a atr gqrs -l vruns_AHA.out 
mxm -r 6207 -a atr gqrs -L hr0.out -m 0

: Record 7201
bxb -r 7201 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 7201 -a atr gqrs -l vruns_AHA.out 
mxm -r 7201 -a atr gqrs -L hr0.out -m 0

: Record 7202
bxb -r 7202 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 7202 -a atr gqrs -l vruns_AHA.out 
mxm -r 7202 -a atr gqrs -L hr0.out -m 0

: Record 7203
bxb -r 7203 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 7203 -a atr gqrs -l vruns_AHA.out 
mxm -r 7203 -a atr gqrs -L hr0.out -m 0

: Record 7204
bxb -r 7204 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 7204 -a atr gqrs -l vruns_AHA.out 
mxm -r 7204 -a atr gqrs -L hr0.out -m 0

: Record 7205
bxb -r 7205 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 7205 -a atr gqrs -l vruns_AHA.out 
mxm -r 7205 -a atr gqrs -L hr0.out -m 0

: Record 7206
bxb -r 7206 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 7206 -a atr gqrs -l vruns_AHA.out 
mxm -r 7206 -a atr gqrs -L hr0.out -m 0

: Record 7207
bxb -r 7207 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 7207 -a atr gqrs -l vruns_AHA.out 
mxm -r 7207 -a atr gqrs -L hr0.out -m 0

: Record 8201
bxb -r 8201 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 8201 -a atr gqrs -l vruns_AHA.out 
mxm -r 8201 -a atr gqrs -L hr0.out -m 0

: Record 8202
bxb -r 8202 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 8202 -a atr gqrs -l vruns_AHA.out 
mxm -r 8202 -a atr gqrs -L hr0.out -m 0

: Record 8203
bxb -r 8203 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 8203 -a atr gqrs -l vruns_AHA.out 
mxm -r 8203 -a atr gqrs -L hr0.out -m 0

: Record 8204
bxb -r 8204 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 8204 -a atr gqrs -l vruns_AHA.out 
mxm -r 8204 -a atr gqrs -L hr0.out -m 0

: Record 8205
bxb -r 8205 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 8205 -a atr gqrs -l vruns_AHA.out 
mxm -r 8205 -a atr gqrs -L hr0.out -m 0

: Record 8206
bxb -r 8206 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 8206 -a atr gqrs -l vruns_AHA.out 
mxm -r 8206 -a atr gqrs -L hr0.out -m 0

: Record 8207
bxb -r 8207 -a atr gqrs -l bxb_AHA.out sd_AHA.out
rxr -r 8207 -a atr gqrs -l vruns_AHA.out 
mxm -r 8207 -a atr gqrs -L hr0.out -m 0

: Generate summary report
echo Beat detection and classification performance >>AHA-report.txt
echo >>AHA-report.txt
sumstats bxb_AHA.out >>AHA-report.txt
echo >>AHA-report.txt
echo Analysis shutdowns >>AHA-report.txt
echo >>AHA-report.txt
sumstats sd_AHA.out >>AHA-report.txt
echo >>AHA-report.txt
echo Ventricular ectopic run detection performance >>AHA-report.txt
echo >>AHA-report.txt
sumstats vruns_AHA.out >>AHA-report.txt
echo >>AHA-report.txt
echo Heart rate measurement number 0 performance >>AHA-report.txt
echo >>AHA-report.txt
sumstats hr0.out >>AHA-report.txt
echo >>AHA-report.txt
echo The evaluation is complete.  Print text file AHA-report.txt
echo to get the results.
