set WFDB=C:\Users\Public\Work\ecg_viewer\assets\ECG_DB\CUDB;
: file: CU-valid.bat	ecgeval		30 July 2026
:
: Evaluate test annotator gqrs on the CU DB

: This file was automatically generated by ecgeval.  Do not edit it
: unless you know what you are doing!

: Record cu01
bxb -r cu01 -a atr gqrs -l bxb.out sd.out
rxr -r cu01 -a atr gqrs -l vruns.out 
mxm -r cu01 -a atr gqrs -L hr0.out -m 0

: Record cu02
bxb -r cu02 -a atr gqrs -l bxb.out sd.out
rxr -r cu02 -a atr gqrs -l vruns.out 
mxm -r cu02 -a atr gqrs -L hr0.out -m 0

: Record cu03
bxb -r cu03 -a atr gqrs -l bxb.out sd.out
rxr -r cu03 -a atr gqrs -l vruns.out 
mxm -r cu03 -a atr gqrs -L hr0.out -m 0

: Record cu04
bxb -r cu04 -a atr gqrs -l bxb.out sd.out
rxr -r cu04 -a atr gqrs -l vruns.out 
mxm -r cu04 -a atr gqrs -L hr0.out -m 0

: Record cu05
bxb -r cu05 -a atr gqrs -l bxb.out sd.out
rxr -r cu05 -a atr gqrs -l vruns.out 
mxm -r cu05 -a atr gqrs -L hr0.out -m 0

: Record cu06
bxb -r cu06 -a atr gqrs -l bxb.out sd.out
rxr -r cu06 -a atr gqrs -l vruns.out 
mxm -r cu06 -a atr gqrs -L hr0.out -m 0

: Record cu07
bxb -r cu07 -a atr gqrs -l bxb.out sd.out
rxr -r cu07 -a atr gqrs -l vruns.out 
mxm -r cu07 -a atr gqrs -L hr0.out -m 0

: Record cu08
bxb -r cu08 -a atr gqrs -l bxb.out sd.out
rxr -r cu08 -a atr gqrs -l vruns.out 
mxm -r cu08 -a atr gqrs -L hr0.out -m 0

: Record cu09
bxb -r cu09 -a atr gqrs -l bxb.out sd.out
rxr -r cu09 -a atr gqrs -l vruns.out 
mxm -r cu09 -a atr gqrs -L hr0.out -m 0

: Record cu10
bxb -r cu10 -a atr gqrs -l bxb.out sd.out
rxr -r cu10 -a atr gqrs -l vruns.out 
mxm -r cu10 -a atr gqrs -L hr0.out -m 0

: Record cu11
bxb -r cu11 -a atr gqrs -l bxb.out sd.out
rxr -r cu11 -a atr gqrs -l vruns.out 
mxm -r cu11 -a atr gqrs -L hr0.out -m 0

: Record cu12
bxb -r cu12 -a atr gqrs -l bxb.out sd.out
rxr -r cu12 -a atr gqrs -l vruns.out 
mxm -r cu12 -a atr gqrs -L hr0.out -m 0

: Record cu13
bxb -r cu13 -a atr gqrs -l bxb.out sd.out
rxr -r cu13 -a atr gqrs -l vruns.out 
mxm -r cu13 -a atr gqrs -L hr0.out -m 0

: Record cu14
bxb -r cu14 -a atr gqrs -l bxb.out sd.out
rxr -r cu14 -a atr gqrs -l vruns.out 
mxm -r cu14 -a atr gqrs -L hr0.out -m 0

: Record cu15
bxb -r cu15 -a atr gqrs -l bxb.out sd.out
rxr -r cu15 -a atr gqrs -l vruns.out 
mxm -r cu15 -a atr gqrs -L hr0.out -m 0

: Record cu16
bxb -r cu16 -a atr gqrs -l bxb.out sd.out
rxr -r cu16 -a atr gqrs -l vruns.out 
mxm -r cu16 -a atr gqrs -L hr0.out -m 0

: Record cu17
bxb -r cu17 -a atr gqrs -l bxb.out sd.out
rxr -r cu17 -a atr gqrs -l vruns.out 
mxm -r cu17 -a atr gqrs -L hr0.out -m 0

: Record cu18
bxb -r cu18 -a atr gqrs -l bxb.out sd.out
rxr -r cu18 -a atr gqrs -l vruns.out 
mxm -r cu18 -a atr gqrs -L hr0.out -m 0

: Record cu19
bxb -r cu19 -a atr gqrs -l bxb.out sd.out
rxr -r cu19 -a atr gqrs -l vruns.out 
mxm -r cu19 -a atr gqrs -L hr0.out -m 0

: Record cu20
bxb -r cu20 -a atr gqrs -l bxb.out sd.out
rxr -r cu20 -a atr gqrs -l vruns.out 
mxm -r cu20 -a atr gqrs -L hr0.out -m 0

: Record cu21
bxb -r cu21 -a atr gqrs -l bxb.out sd.out
rxr -r cu21 -a atr gqrs -l vruns.out 
mxm -r cu21 -a atr gqrs -L hr0.out -m 0

: Record cu22
bxb -r cu22 -a atr gqrs -l bxb.out sd.out
rxr -r cu22 -a atr gqrs -l vruns.out 
mxm -r cu22 -a atr gqrs -L hr0.out -m 0

: Record cu23
bxb -r cu23 -a atr gqrs -l bxb.out sd.out
rxr -r cu23 -a atr gqrs -l vruns.out 
mxm -r cu23 -a atr gqrs -L hr0.out -m 0

: Record cu24
bxb -r cu24 -a atr gqrs -l bxb.out sd.out
rxr -r cu24 -a atr gqrs -l vruns.out 
mxm -r cu24 -a atr gqrs -L hr0.out -m 0

: Record cu25
bxb -r cu25 -a atr gqrs -l bxb.out sd.out
rxr -r cu25 -a atr gqrs -l vruns.out 
mxm -r cu25 -a atr gqrs -L hr0.out -m 0

: Record cu26
bxb -r cu26 -a atr gqrs -l bxb.out sd.out
rxr -r cu26 -a atr gqrs -l vruns.out 
mxm -r cu26 -a atr gqrs -L hr0.out -m 0

: Record cu27
bxb -r cu27 -a atr gqrs -l bxb.out sd.out
rxr -r cu27 -a atr gqrs -l vruns.out 
mxm -r cu27 -a atr gqrs -L hr0.out -m 0

: Record cu28
bxb -r cu28 -a atr gqrs -l bxb.out sd.out
rxr -r cu28 -a atr gqrs -l vruns.out 
mxm -r cu28 -a atr gqrs -L hr0.out -m 0

: Record cu29
bxb -r cu29 -a atr gqrs -l bxb.out sd.out
rxr -r cu29 -a atr gqrs -l vruns.out 
mxm -r cu29 -a atr gqrs -L hr0.out -m 0

: Record cu30
bxb -r cu30 -a atr gqrs -l bxb.out sd.out
rxr -r cu30 -a atr gqrs -l vruns.out 
mxm -r cu30 -a atr gqrs -L hr0.out -m 0

: Record cu31
bxb -r cu31 -a atr gqrs -l bxb.out sd.out
rxr -r cu31 -a atr gqrs -l vruns.out 
mxm -r cu31 -a atr gqrs -L hr0.out -m 0

: Record cu32
bxb -r cu32 -a atr gqrs -l bxb.out sd.out
rxr -r cu32 -a atr gqrs -l vruns.out 
mxm -r cu32 -a atr gqrs -L hr0.out -m 0

: Record cu33
bxb -r cu33 -a atr gqrs -l bxb.out sd.out
rxr -r cu33 -a atr gqrs -l vruns.out 
mxm -r cu33 -a atr gqrs -L hr0.out -m 0

: Record cu34
bxb -r cu34 -a atr gqrs -l bxb.out sd.out
rxr -r cu34 -a atr gqrs -l vruns.out 
mxm -r cu34 -a atr gqrs -L hr0.out -m 0

: Record cu35
bxb -r cu35 -a atr gqrs -l bxb.out sd.out
rxr -r cu35 -a atr gqrs -l vruns.out 
mxm -r cu35 -a atr gqrs -L hr0.out -m 0

: Generate summary report
echo Beat detection and classification performance >>CU-report.txt
echo >>CU-report.txt
sumstats bxb.out >>CU-report.txt
echo >>CU-report.txt
echo Analysis shutdowns >>CU-report.txt
echo >>CU-report.txt
sumstats sd.out >>CU-report.txt
echo >>CU-report.txt
echo Ventricular ectopic run detection performance >>CU-report.txt
echo >>CU-report.txt
sumstats vruns.out >>CU-report.txt
echo >>CU-report.txt
echo Heart rate measurement number 0 performance >>CU-report.txt
echo >>CU-report.txt
sumstats hr0.out >>CU-report.txt
echo >>CU-report.txt
echo The evaluation is complete.  Print text file CU-report.txt
echo to get the results.
